
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebUI.Models
{

using System;
    
public partial class Address
{

    public string Line1 { get; set; }

    public string Suburb { get; set; }

    public string State { get; set; }

    public string Postcode { get; set; }

    public string Line2 { get; set; }

    public string PlaceId { get; set; }

    public Nullable<double> PlaceLatitude { get; set; }

    public Nullable<double> PlaceLongitude { get; set; }

}

}
