
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebUI.Models
{

using System;
    using System.Collections.Generic;
    
public partial class BusinessLocation
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public BusinessLocation()
    {

        this.Enabled = true;

        this.InternalLocations = new HashSet<InternalLocation>();

        this.ShiftTemplates = new HashSet<ShiftTemplate>();

        this.ShiftBlocks = new HashSet<ShiftBlock>();

        this.EmployerRequests = new HashSet<EmployerRequest>();

        this.Employees = new HashSet<Employee>();

        this.EmployeeRequests = new HashSet<EmployeeRequest>();

        this.Managers = new HashSet<Employee>();

        this.Rosters = new HashSet<Roster>();

        this.TimeCards = new HashSet<TimeCard>();

        this.Address = new Address();

    }


    public System.Guid Id { get; set; }

    public string Name { get; set; }

    public string Phone { get; set; }

    public bool Enabled { get; set; }



    public Address Address { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<InternalLocation> InternalLocations { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ShiftTemplate> ShiftTemplates { get; set; }

    public virtual BusinessPreferences BusinessPreferences { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ShiftBlock> ShiftBlocks { get; set; }

    public virtual Business Business { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<EmployerRequest> EmployerRequests { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Employee> Employees { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<EmployeeRequest> EmployeeRequests { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Employee> Managers { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Roster> Rosters { get; set; }

    public virtual PaymentDetails PaymentDetails { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TimeCard> TimeCards { get; set; }

}

}
