
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebUI.Models
{

using System;
    

public enum EventFrequency : int
{

    Weekly = 0,

    Fortnightly = 1,

    Monthly = 2,

    Annually = 3,

}

}
