
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebUI.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ExternalShiftSkills
{

    public System.Guid Id { get; set; }

    public System.Guid ExternalShiftBroadcastId { get; set; }

    public System.Guid IndustrySkillsId { get; set; }



    public virtual ExternalShiftBroadcast ExternalShiftBroadcast { get; set; }

    public virtual IndustrySkills IndustrySkill { get; set; }

}

}
