
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebUI.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ExternalShiftBroadcast
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ExternalShiftBroadcast()
    {

        this.Shifts = new HashSet<Shift>();

        this.ShiftQualifications = new HashSet<ExternalShiftQualification>();

        this.ShiftSkills = new HashSet<ExternalShiftSkills>();

        this.ExternalShiftRequests = new HashSet<ExternalShiftRequest>();

    }


    public System.Guid Id { get; set; }

    public string Description { get; set; }

    public decimal Wage { get; set; }

    public ExternalShiftStatus Status { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Shift> Shifts { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ExternalShiftQualification> ShiftQualifications { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ExternalShiftSkills> ShiftSkills { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ExternalShiftRequest> ExternalShiftRequests { get; set; }

}

}
