
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebUI.Models
{

using System;
    using System.Collections.Generic;
    
public partial class IndustrySkills
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public IndustrySkills()
    {

        this.UserSkills = new HashSet<UserSkills>();

        this.ShiftSkills = new HashSet<ExternalShiftSkills>();

    }


    public System.Guid Id { get; set; }

    public string Name { get; set; }

    public int IndustryTypesID { get; set; }



    public virtual IndustryTypes IndustryType { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<UserSkills> UserSkills { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ExternalShiftSkills> ShiftSkills { get; set; }

}

}
