

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebUI.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class DataModelDbContext : DbContext
{
    public DataModelDbContext()
        : base("name=DataModelDbContext")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<BusinessLocation> BusinessLocations { get; set; }

    public virtual DbSet<BusinessType> BusinessTypes { get; set; }

    public virtual DbSet<Employee> Employees { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<UserProfile> UserProfiles { get; set; }

    public virtual DbSet<security_Membership> security_Membership { get; set; }

    public virtual DbSet<security_Role> security_Role { get; set; }

    public virtual DbSet<EmployerRequest> EmployerRequests { get; set; }

    public virtual DbSet<InternalLocation> InternalLocations { get; set; }

    public virtual DbSet<ShiftTemplate> ShiftTemplates { get; set; }

    public virtual DbSet<Roster> Rosters { get; set; }

    public virtual DbSet<Shift> Shifts { get; set; }

    public virtual DbSet<BusinessPreferences> BusinessPreferences { get; set; }

    public virtual DbSet<ShiftChangeRequest> ShiftChangeRequests { get; set; }

    public virtual DbSet<Schedule> Schedules { get; set; }

    public virtual DbSet<EmployeeRequest> EmployeeRequests { get; set; }

    public virtual DbSet<ShiftBlock> ShiftBlocks { get; set; }

    public virtual DbSet<UserPreferences> UserPreferences { get; set; }

    public virtual DbSet<Business> Businesses { get; set; }

    public virtual DbSet<RecurringShiftChangeRequest> RecurringShiftChangeRequests { get; set; }

    public virtual DbSet<security_OAuthMembership> security_OAuthMembership { get; set; }

    public virtual DbSet<PaymentDetails> PaymentDetails { get; set; }

    public virtual DbSet<TimeCard> TimeCards { get; set; }

    public virtual DbSet<Timesheet> Timesheets { get; set; }

    public virtual DbSet<TimesheetEntry> TimesheetEntries { get; set; }

    public virtual DbSet<IndustryTypes> IndustryTypes { get; set; }

    public virtual DbSet<WorkHistory> WorkHistories { get; set; }

    public virtual DbSet<Qualificationslookup> Qualificationslookups { get; set; }

    public virtual DbSet<UserQualification> UserQualifications { get; set; }

    public virtual DbSet<OtherQualification> OtherQualifications { get; set; }

    public virtual DbSet<IndustrySkills> IndustrySkills { get; set; }

    public virtual DbSet<UserSkills> UserSkills { get; set; }

    public virtual DbSet<ExternalShiftBroadcast> ExternalShiftBroadcasts { get; set; }

    public virtual DbSet<ExternalShiftQualification> ExternalShiftQualifications { get; set; }

    public virtual DbSet<ExternalShiftSkills> ExternalShiftSkills { get; set; }

    public virtual DbSet<ExternalShiftRequest> ExternalShiftRequests { get; set; }

    public virtual DbSet<UserRecommendations> UserRecommendations { get; set; }

    public virtual DbSet<UserSkillEndorsements> UserSkillEndorsements { get; set; }

    public virtual DbSet<Messages> Messages { get; set; }

}

}

