
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebUI.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Qualificationslookup
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Qualificationslookup()
    {

        this.UserQualifications = new HashSet<UserQualification>();

        this.ShiftQualifications = new HashSet<ExternalShiftQualification>();

    }


    public System.Guid QualificationId { get; set; }

    public string QualificationName { get; set; }

    public int IndustryTypesID { get; set; }



    public virtual IndustryTypes IndustryType { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<UserQualification> UserQualifications { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ExternalShiftQualification> ShiftQualifications { get; set; }

}

}
