
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebUI.Models
{

using System;
    using System.Collections.Generic;
    
public partial class RecurringShiftChangeRequest
{

    public System.Guid Id { get; set; }

    public ShiftRequestType Type { get; set; }

    public string Reason { get; set; }

    public RequestStatus Status { get; set; }

    public System.DateTime OccurenceDate { get; set; }

    public System.DateTime CreatedDate { get; set; }

    public Nullable<System.DateTime> ActionedDate { get; set; }

    public string ActionedComment { get; set; }



    public virtual ShiftTemplate ShiftTemplate { get; set; }

    public virtual Employee ActionedBy { get; set; }

}

}
