//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUI.Models
{
    using System;
    
    public enum ShiftFrequency : int
    {
        Weekly = 0,
        Fortnight1 = 1,
        Fortnight2 = 2,
        Monthly = 3,
        OneOff = 4
    }
}
