//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeCard
    {
        public System.Guid Id { get; set; }
        public System.DateTime ClockIn { get; set; }
        public string ClockInComment { get; set; }
        public Nullable<System.DateTime> ClockOut { get; set; }
        public string ClockOutComment { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual BusinessLocation BusinessLocation { get; set; }
        public virtual Employee LastUpdatedBy { get; set; }
        public virtual Shift Shift { get; set; }
        public virtual TimesheetEntry TimesheetEntry { get; set; }
        public virtual Roster Roster { get; set; }
    }
}
