//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimesheetEntry
    {
        public System.Guid Id { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public Nullable<System.DateTime> FinishDateTime { get; set; }
        public bool Approved { get; set; }
        public Nullable<System.DateTime> ApprovedDateTime { get; set; }
    
        public virtual UserProfile ApprovedBy { get; set; }
        public virtual TimeCard TimeCard { get; set; }
    }
}
