//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSkillEndorsements
    {
        public System.Guid Id { get; set; }
    
        public virtual UserSkills UserSkill { get; set; }
        public virtual UserProfile UserProfileUserRecommendedBY { get; set; }
        public virtual UserProfile UserProfileUserBeingRecommended { get; set; }
    }
}
