//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPreferences
    {
        public System.Guid Id { get; set; }
        public bool InternalAvailableShifts { get; set; }
        public bool ExternalShiftInfo { get; set; }
        public bool ExternalAvailableShifts { get; set; }
        public int DistanceTravel { get; set; }
        public int ShiftReminderLength { get; set; }
        public bool NotifyByApp { get; set; }
        public bool NotifyBySMS { get; set; }
        public bool NotifyByEmail { get; set; }
        public bool TimeFormat24Hr { get; set; }
        public bool MonthCalView { get; set; }
        public byte[] ImageData { get; set; }
        public string ImageType { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
