//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSkills
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserSkills()
        {
            this.UserSkillEndorsements = new HashSet<UserSkillEndorsements>();
        }
    
        public System.Guid UserSkillId { get; set; }
        public System.Guid UserProfileId { get; set; }
        public System.Guid IndustrySkillsId { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
        public virtual IndustrySkills IndustrySkill { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserSkillEndorsements> UserSkillEndorsements { get; set; }
    }
}
