//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserQualification
    {
        public System.Guid UserQualificationId { get; set; }
        public System.Guid QualificationslookupQualificationId { get; set; }
        public System.Guid UserProfileId { get; set; }
    
        public virtual Qualificationslookup Qualificationslookup { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
